import React, { Component } from 'react'
import PropTypes from 'prop-types'
import sass from '../scss/application.scss'


class Important extends Component {
   
	render() {
		return (
			<article className="artPDF">
			<div>
				<p className="pdfText">
					<span className="addBold">IMPORTANT NOTICE</span><br /><br />
					ALL SAWMILL EQUIPMENT AND CONTROLS SHOULD BE INSTALLED, OPERATED AND SERVICED BY TRAINED PERSONNEL ONLY. SUCH EQUIPMENT IS POTENTIALLY HAZARDOUS, AND EXTREME CAUTION MUST ALWAYS BE EXERCISED. IT IS THE OWNER’S RESPONSIBILITY TO USE ONLY TRAINED PERSONNEL.<br /><br />
					MOST ITEMS SUPPLIED BY THE MANUFACTURERS ARE NOT COMPLETE, READY-TO-OPERATE MACHINES. PROPER INSTALLATION, ALIGNMENT AND PRE-OPERATION CHECKS MUST BE COMPLETED.<br /><br />WHEN INSTALLING THIS EQUIPMENT REFER TO APPLICABLE NATIONAL SAFETY STANDARDS, OSHA REGULATIONS, NATIONAL ELECTRICAL CODES, AND APPLICABLE STATE AND LOCAL CODES. FOR YOUR CONVENIENCE, A LISTING OF 'PRIMARY APPLICABLE SAFETY STANDARDS FOR SAWMILL MACHINERY' IS ENCLOSED (2-60A).<br /><br />
					EQUIPMENT SHOULD BE INSTALLED BY QUALIFIED AND PROPERLY LICENSED AND TRAINED PERSONNEL AND IF REQUIRED, INSPECTED BY AUTHORIZED STATE AND/OR LOCAL AUTHORITIES BEFORE START-UP.<br /><br /> 
					READY SCAN<br /><br />
					<span className="addBold">IMPORTANT NOTICE</span><br /><br />
					THE MANUFACTURER IS CONCERNED ABOUT SAFETY AND INCORPORATES VARIOUS SAFETY FEATURES IN THE CONTROL SYSTEM. HOWEVER, NONE OF THESE ARE TRUE LOCKOUT DEVICES. IT IS THE OWNER’S RESPONSIBILITY TO SEE THAT LOCKOUT DEVICES AND/OR OTHER DEVICES THAT MEET OR EXCEED OSHA AND/OR STATE LOCAL REQUIREMENTS ARE OBTAINED, INSTALLED AND USED PROPERLY. OWNERS ARE ALSO RESPONSIBLE FOR ESTABLISHING OPERATION, LOCKOUT/TAGOUT, AND SERVICING PROCEDURES FOR THE CONTROL SYSTEM AS WELL AS TRAINING PERSONNEL.<br /><br />
					SPECIFIC WARNINGS ARE HIGH-LIGHTED ON THE VARIOUS PAGES OF THIS MANUAL. THESE SHOULD BE READ AND UNDERSTOOD BY OPERATING PERSONNEL PRIOR TO START-UP OF THE CONTROL SYSTEM. <br /><br />
				</p>
			</div>
			</article>
		)
	}
}


export default Important;
